
version: 1.2.0-dev-{build}
branches:
  only:
  - main
skip_commits:
  files:
    - README.md
image: Visual Studio 2022
configuration: Release
before_build:
- ps: '& .\appveyor-prebuild.ps1'
build:
  project: OtpCore.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: hCf3CYxDjjUdIeMlGv38eURitGnfsq5AvhEUOTPTATxqzROOjBbHm/mkRyvfocYD
notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: OtpCore build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
