
version: 1.1.0-release-{build}
branches:
  only:
  - main
  - release-1.1
image: Visual Studio 2022
configuration: Release
before_build:
- ps: '& .\appveyor-prebuild.ps1'
build:
  project: OtpCore.sln
  publish_nuget: true
  publish_nuget_symbols: true
  use_snupkg_format: true
  parallel: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: YHb6jbBI5yVXOUk8PhT6LyYlxXx3DRFBOMFlbmFdIZimYJYrrzGo7nOZiUNULa4P
notifications:
- provider: Email
  to:
  - petrsnd@gmail.com
  subject: OtpCore build is failing
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false